{% set name = "fftlog" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 965b41abc371471b4862e71081dac5954caa4db7f4abafe775d371f765548cae

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv  # [unix]
    - {{ PYTHON }} -m pip install . -vv --global-option=build_ext --global-option --compiler=mingw32  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
  host:
    - meson-python
    - wheel
    - charset-normalizer
    - pip
    - numpy >=1.26
    - python
    - m2w64-gcc-libgfortran   # [win]
  run:
    - python
    - numpy >=1.26
    - scipy

test:
  requires:
    - python
  imports:
    - fftlog

about:
  home: https://github.com/emsig/fftlog
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: "Logarithmic Fast Fourier Transform"
  description: |
    A simple python-wrapper for the logarithmic FFT code FFTLog
    as presented in Appendix B of Hamilton (2000) and published at
    casa.colorado.edu/~ajsh/FFTLog.
  doc_url: https://pyfftlog.readthedocs.io/
  dev_url: https://github.com/emsig/fftlog

extra:
  recipe-maintainers:
    - prisae
